---
title: "Proposal"
output: html_document
---

1. A one sentence description of your high-level goal.


2. A one to two paragraph description of your goals, including your motivation.

In class, we learned about scale_color_vidiris and scale_fill_viridis, two functions in ggplot that are designed to make colored graphs more accessible to color-blind viewers. All of us were very interested in further exploring accessibility concerns for the colorblind community, so we would like to implement a sliding color scale to allow noncolorblind viewers to understand these accessibility concerns. This sliding scale would apply different filters for different types of colorblindness, such as deuteranopia, protanopia, and tritanopia. By exploring different types, we will play around with the color use and theme design as well as raise awareness for the variety of colorblindness out there. We think it is extremely important for members of the noncolorblind community to understand accessibility issues in the plots and images they make. We can all move towards more accessible and equitable visualizations with our project.
 
3. A weekly “plan of attack” outlining your steps to complete your project and including the team member(s) assigned to that task.


4. The final organization of your project repository. This means describing the project organization in your proposal as well as implementing that organization in your repo. Create any folders needed and place a README.md in each folder explaining what goes in there.


