---
title: "Project Proposal"
author: "Stats R Us"
output: github_document
---

**1. A one sentence description of your high-level goal.**

We want to build a Shiny app to help users understand color blindness by building “filters” for photos representing different types of color deficiency. 

**2. A one to two paragraph description of your goals, including your motivation.**

In class, we learned about scale_color_vidiris and scale_fill_viridis, two functions in ggplot that are designed to make colored graphs more accessible to color-blind viewers. All of us were very interested in further exploring accessibility concerns for the colorblind community, so we would like to implement a sliding color scale to allow noncolorblind viewers to understand these accessibility concerns. This sliding scale would apply different filters for different types of colorblindness, such as deuteranopia, protanopia, and tritanopia. By exploring different types, we will play around with the color use and theme design as well as raise awareness for the variety of colorblindness out there. We think it is extremely important for members of the noncolorblind community to understand accessibility issues in the plots and images they make. We can all move towards more accessible and equitable visualizations with our project.

One package that we will use in this app will be the `imager` library, which contains a large array of functions for working with image data. As we allow users to input images and filter them for different types of color blindness, as well as creating a colorblind test, the functionality of this package will be helpful. A dataset we may choose to incorporate when talking about the significance of our project can be found at https://data.world/datacrunch/prevalence-of-vision-problems-in-the-u-s, in order to compare the prevalence of commonly known vision problems to rates of less commonly known types of color blindness, statistics about which will be referenced from https://iristech.co/statistics/. 

**3. A weekly “plan of attack” outlining your steps to complete your project and including the team member(s) assigned to that task.**

DUE DATES:
Proposal due November 5.
Revised proposal due November 12.
Write-up and presentation due December 3.


Proposal (Due November 5):

- One sentence description: Kate (done by 11/1)
- Motivation: Sophie (done by 11/1)
- Weekly plan of attack: Sophie and Kate (done by 11/1)
- Goals: Parker and Holly (done by 11/1)
- Organization: Holly (done by 11/1)
- Dates: 
  - Finish rough draft of all of our parts by end of day on 11/1
  - All members read over entire rough draft and make edits by 11/3
  - Final draft of proposal complete by end of day 11/3


Revised Proposal (Due November 12):

- Review comments individually on 11/9
- Meet on 11/10 to revise proposal
- Close all comments by 11/11
- Submit updated proposal by end of day 11/11


Write-Up (Due December 3):

- Introduction (by 11/13):
  - Sophie and Parker
- Sliding Color Scale (by 11/17):
  - As a team: study room reserved for week of 11/15
  - Find images that are conducive to our goals
    - Parker
- Conclusion (by 11/25):
  - Holly and Kate


Website (Due December 3): 

- Our project is a Shiny App and therefore is a website
- We will add a page to our website by the end of November including our Write-Up
Sophie


Presentation (Due December 3):

- Our presentation will include a demo of our website 
- Slides including our motivation and significance of the social impact of understanding color blindness
  - Make slides by end of November: 
    - Kate and Holly
- Entire team practice and make final edits to presentation and write-up on 12/2 
  - Link group study 3 reserved 7-11pm


**4. The final organization of your project repository.** 

There will be two main folders created under the project repository, one containing the major RMD file with the Shiny app design and the other including all images we will be using to work on the different types of filters. A separate presentation folder will also be created using xaringan. 

Folder structure: 
App (.rmd, .html (website), README describing sections of website and user interface)
Data (images that will be used on website)
Presentation (using xaringan) 



