---
title: "whyCBmatters"
output: html_document
---

```{r packages}
library(tidyverse)
library(waffle)
library(hrbrthemes)
library(png)
```

```{r make-df}
cb <- tribble(
  ~entity, ~of100,
  "Color Blind Males",   80,
  "Normal Vision Males",   420,
  "Color Blind Females",   4,
  "Normal Vision Females", 496
)

man <- readPNG("data/man.png", native = TRUE, info = TRUE)

```

```{r cb-viz}
waffle(cb$of100, rows = 40, size=1)
```

```{r}
# ggplot(cb, aes(fill = Source, values = of100, label=entity)) +
# 
#   geom_pictogram(n_rows = 40, size = 7) +  #, aes(colour = Source), flip = TRUE) +
# 
#   scale_label_pictogram(
# 
#     name = NULL,
# 
#     values = c("circle", "fire", "gas-pump"),
# 
#     labels = c("Coal", "Natural Gas", "Oil")
# 
#   ) +
# 
#   scale_color_manual(
# 
#     name = NULL,
# 
#     values = c("#a40000", "#c68958", "#ae6056"),
# 
#     labels = c("Coal", "Natural Gas", "Oil")
# 
#   ) +
# 
#   coord_equal() + facet_wrap(~Entity, ncol=3)+
# 
#   labs(
# 
#     title = "Use of coal, natural gas and oil by continent",
# 
#     subtitle="1 unit = 1,000 terawatt-hours",
# 
#     caption="Source: Our World in Data, 2018"
# 
#   ) + ylab("") + xlab("") +
# 
#   theme(panel.grid.major = element_blank(),
# 
#         panel.grid.minor = element_blank(),
# 
#         panel.border = element_blank(),
# 
#         panel.background = element_blank(),
# 
#         strip.background = element_blank(),
# 
#         axis.text= element_blank(),
# 
#         axis.ticks= element_blank(),
# 
#         legend.key.height = unit(1.5, "line"),
# 
#         legend.key=element_blank(),
# 
#         legend.position = c(0.15,-0.15),
# 
#         legend.direction='horizontal'
# 
#   )


```



